name: Matrix Include

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Base matrix variables
        version: [1, 2]
        os: [ubuntu-latest, windows-latest]
        include:
          - error-color: "red" 
          - os: "ubuntu-latest" 
            comment-color: "blue" 
          - os: "macos-latest" 
            comment-color: "yellow" 
    steps:
      - name: Print current matrix configuration
        run: |
          echo "Running on OS: ${{ matrix.os }}"
          echo "Using Node Version: ${{ matrix.version }}"
