name: My first check reaction

# This is the trigger - the part GH-200 will ask you about
on:
  check_run:
    types: [completed]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "A check just finished! Its name was ${{ github.event.check_run.name }} and result was ${{ github.event.check_run.conclusion }}"
