on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run composite action
        id: my-action
        uses: ./.github/actions/outputs

      - name: Display result
        run: 'echo "Script Result: ${{ steps.my-action.outputs.script-result }}"'