name: Consume JS Action Example

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-custom-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies for action
        run: npm install
        working-directory: .github/actions/mask-secret-action

      - name: Run JavaScript Action
        id: decode-step
        uses: ./.github/actions/mask-secret-action
        with:
          # Base64 encoded string for "supersecretpassword"
          encoded_secret: 'c3VwZXJzZWNyZXRwYXNzd29yZA=='

      - name: Verify Secret Redaction in Log
        run: |
          echo "The secret output is: ${{ steps.decode-step.outputs.masked_output }}"
