name: Workflow Outputs Example
on: [push]

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable-output.yml

  use-data:
    needs: call-reusable
    runs-on: ubuntu-latest
    steps:
      - run: echo "Result was ${{ needs.call-reusable.outputs.compiled-result }}"

# This workflow is part of reusable-output.yml demonstration
